import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Nav from "../Layout/Nav";
import Homee from './../Components/Home.js';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <Nav>
       <Homee />
       </Nav>
      </main>
    </div>
  )
}
