import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Nav from '../Layout/Nav';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <Nav>

       </Nav>
      </main>

      <footer className={styles.footer}>
       <h2>Created by Niles</h2>
      </footer>
    </div>
  )
}
